name: Linting

on:
  push:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          commit_message: 'lint: run prettier'
          prettier_options: -w .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.2
          run_install: true
      - name: Run ESLint
        run: pnpm run lint
